#include "tests/TestTexture2D.h"
#include "tests/TestBatchRender.h"
#include "tests/TestLearningTexture.h"
#include "tests/TestLearningCoordSys.h"
#include "tests/LightTest/TestLight.h" 
#include "tests/LightTest/TestMaterial.h"
#include "tests/LightTest/TestMap.h"